# Impliment a basic neural network on Brestcancer dataset
- it is just to understand the workflow of the training pipline

## work flow
- Load the dataset
- Basic preprocessing
- training Process
    - Create the model
    - forward pass
    - Loss calculation
    - Backprop
    - Parameters Update
- Model evaluation

In [1]:
import numpy as np
import pandas as pd 
import torch 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
df.shape

(569, 31)

- train test split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)

- scaling

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[-0.13414002, -0.03788016, -0.10508776, ...,  0.40455881,
        -0.25752451,  0.28688539],
       [-0.67146305, -0.39925423, -0.65739338, ..., -0.19849773,
        -0.69199706, -0.34123738],
       [-0.54205541, -0.29337393, -0.5588982 , ..., -0.39156696,
         0.51668597, -0.50784665],
       ...,
       [-0.63770454,  0.51684055, -0.61913492, ..., -0.40356733,
        -0.97456755,  0.93300427],
       [-0.58425356, -1.50869565, -0.61872792, ..., -0.66560071,
        -0.63319627, -0.25938404],
       [-1.09063129, -1.62838642, -1.07009632, ..., -0.71557693,
         0.05771309, -0.36155558]])

In [10]:
y_train

423    B
530    B
367    B
434    B
273    B
      ..
179    B
235    B
450    B
158    B
390    B
Name: diagnosis, Length: 455, dtype: object

- Label Encoding

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0])

- numpy array to PyTorch tensors

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
X_train_tensor.shape, X_train_tensor

(torch.Size([455, 30]),
 tensor([[-0.1341, -0.0379, -0.1051,  ...,  0.4046, -0.2575,  0.2869],
         [-0.6715, -0.3993, -0.6574,  ..., -0.1985, -0.6920, -0.3412],
         [-0.5421, -0.2934, -0.5589,  ..., -0.3916,  0.5167, -0.5078],
         ...,
         [-0.6377,  0.5168, -0.6191,  ..., -0.4036, -0.9746,  0.9330],
         [-0.5843, -1.5087, -0.6187,  ..., -0.6656, -0.6332, -0.2594],
         [-1.0906, -1.6284, -1.0701,  ..., -0.7156,  0.0577, -0.3616]],
        dtype=torch.float64))

In [15]:
X_train.shape

(455, 30)

# Defining the model

In [16]:
class MySimpleNN():
    def __init__(self,X):

        self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad= True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon,  1 - epsilon)

        # claculating the loss 
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1-y_pred)).mean()
        return loss

- important Parameters

In [17]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [18]:
# create model 
model = MySimpleNN(X_train_tensor)
model.weights

tensor([[0.8365],
        [0.5907],
        [0.1883],
        [0.6911],
        [0.3845],
        [0.8160],
        [0.7334],
        [0.1268],
        [0.7210],
        [0.7543],
        [0.1858],
        [0.0958],
        [0.9057],
        [0.4981],
        [0.7660],
        [0.3948],
        [0.0609],
        [0.2236],
        [0.4659],
        [0.4805],
        [0.9532],
        [0.9821],
        [0.5042],
        [0.3368],
        [0.4240],
        [0.4260],
        [0.5243],
        [0.9104],
        [0.2222],
        [0.5186]], dtype=torch.float64, requires_grad=True)

In [19]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [20]:
# definr loop

for epoch in range(epochs):
    
    # forward pass 
    y_pred = model.forward(X_train_tensor)
    
    # loss calculate 
    loss = model.loss_function(y_pred, y_train_tensor)
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')
    # baclward pass

    loss.backward()

    # Parameters update  (we don't need to trach gradients dugring updating so we will of the greadints)
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients 
    model.weights.grad.zero_()
    model.bias.grad.zero_()

Epoch: 1, Loss: 3.7180316747210087
Epoch: 2, Loss: 3.605412885782081
Epoch: 3, Loss: 3.48754029976182
Epoch: 4, Loss: 3.3659512068738273
Epoch: 5, Loss: 3.2388315080655716
Epoch: 6, Loss: 3.1068071820819867
Epoch: 7, Loss: 2.972508363114881
Epoch: 8, Loss: 2.8353624452215276
Epoch: 9, Loss: 2.689991354823611
Epoch: 10, Loss: 2.5380554471366272
Epoch: 11, Loss: 2.383442774332872
Epoch: 12, Loss: 2.226824529342007
Epoch: 13, Loss: 2.070925579723011
Epoch: 14, Loss: 1.9134851141776565
Epoch: 15, Loss: 1.7606974448123462
Epoch: 16, Loss: 1.6119190426213237
Epoch: 17, Loss: 1.4645920281076352
Epoch: 18, Loss: 1.3300007771455427
Epoch: 19, Loss: 1.210042544347342
Epoch: 20, Loss: 1.1063727243819006
Epoch: 21, Loss: 1.019987572176693
Epoch: 22, Loss: 0.950790130822448
Epoch: 23, Loss: 0.8974514478871475
Epoch: 24, Loss: 0.8576734657629415
Epoch: 25, Loss: 0.8286462597243271

In [21]:
model.weights, model.bias

(tensor([[ 0.3482],
         [ 0.1894],
         [-0.3219],
         [ 0.2109],
         [-0.0547],
         [ 0.1720],
         [ 0.0849],
         [-0.5316],
         [ 0.2900],
         [ 0.4686],
         [-0.2740],
         [-0.0719],
         [ 0.4432],
         [ 0.0989],
         [ 0.5565],
         [-0.0927],
         [-0.3449],
         [-0.2872],
         [ 0.2952],
         [ 0.1063],
         [ 0.4138],
         [ 0.5623],
         [-0.0533],
         [-0.1817],
         [-0.0269],
         [-0.1624],
         [-0.0942],
         [ 0.2508],
         [-0.1424],
         [ 0.0542]], dtype=torch.float64, requires_grad=True),
 tensor([-0.1364], dtype=torch.float64, requires_grad=True))

- model evaluation

In [22]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5152354836463928

# do it after lecture 4

In [38]:
class MySimpleNN2(nn.Module):

    def __init__ (self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 1), # (num of inputs, num of outputs)
            nn.Sigmoid()
        )
        

    def forward(self, features):
        out = self.network(features)

        return out

In [39]:
# Built-in BCEloss
loss_function = nn.BCELoss()

In [41]:
# definr loop

model1 = MySimpleNN2(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model1.parameters(), lr = 0.2)


for epoch in range(epochs):
    
    # forward pass 
    y_pred = model1(X_train_tensor.float())
    
    # loss calculate 
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

    # zero gradients 
    optimizer.zero_grad()

    # baclward pass

    loss.backward()

RuntimeError: Found dtype Long but expected Float

In [ ]:
print(3)